version: '2'
services:
    histrikopoc-app:
        image: histrikopoc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://histrikopoc-mysql:3306/histrikopoc?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    histrikopoc-mysql:
        extends:
            file: mysql.yml
            service: histrikopoc-mysql
